// sync-tracker.mjs — regenerate the tracker's on-chain data FROM THE CHAIN, and
// re-copy the shared engine files. Safe to re-run at any point during a run.
//
// Hand-maintaining 31 inscription IDs across two repos is how this project's data
// goes stale (see memory/todo.md "Why this file was wrong"). Nothing here is typed
// by hand: children come from the engine's /r/children, and every field comes from
// that piece's own /r/metadata and /inscription.
//
//   node sync-tracker.mjs            # report only
//   node sync-tracker.mjs --write    # write inscriptions.ts + copy shared files

import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT    = dirname(fileURLToPath(import.meta.url));
const TRACKER = join(ROOT, '..', 'cessation-tracker');
const ORD     = 'http://127.0.0.1:80';
const WRITE   = process.argv.includes('--write');

if (!existsSync(TRACKER)) { console.error(`tracker not found at ${TRACKER}`); process.exit(1); }
const ENGINE = readFileSync(join(ROOT, 'ENGINE_ID.txt'), 'utf8').trim();

// the engine's own CBOR decoder, so the tracker is fed exactly what a piece reads
const src = readFileSync(join(ROOT, 'src/main.js'), 'utf8');
const cborDecode = new Function(`${src.match(/^function cborDecode\(hex\) \{[\s\S]*?\n\}/m)[0]}; return cborDecode;`)();

const j = async (u) => { const r = await fetch(ORD + u, { headers: { accept: 'application/json' } });
                         if (!r.ok) throw new Error(`${u} -> ${r.status}`); return r.json(); };

// every child of the engine, paginated
const ids = [];
for (let page = 0; page < 100; page++) {
  const p = await j(`/r/children/${ENGINE}/inscriptions/${page}`).catch(() => null)
         ?? (page === 0 ? await j(`/r/children/${ENGINE}`) : { ids: [], more: false });
  const got = p.ids ?? (p.children ?? []).map(c => c.id ?? c);
  ids.push(...got);
  if (!p.more) break;
}
console.log(`engine ${ENGINE.slice(0, 16)}… has ${ids.length} children on chain`);

const rows = [];
for (const id of ids) {
  let meta = null;
  try { const hex = await j(`/r/metadata/${id}`); meta = cborDecode(String(hex).trim()); }
  catch { console.log(`  ${id.slice(0,16)}… no metadata — skipped (not a piece)`); continue; }
  if (!meta || typeof meta.pieceIndex !== 'number') { console.log(`  ${id.slice(0,16)}… no pieceIndex — skipped`); continue; }
  const info = await j(`/inscription/${id}`);
  rows.push({ idx: meta.pieceIndex, inscriptionId: id, hashTail: meta.hashTail,
              inscriptionUnix: meta.inscriptionUnix, blockHeight: info.height,
              sat: info.sat, date: meta.dataset?.date });
}
rows.sort((a, b) => a.idx - b.idx);

// how many entries should the array have? follow the local dataset count, never a
// hardcoded number — the collection is open-ended.
const ds = (await import('./data/health_data_sets.js')).healthDataSets;
const N = Math.max(ds.length, rows.length ? rows[rows.length - 1].idx + 1 : 0);

console.log(`\npiece  sat              block    ht   date`);
for (let i = 0; i < N; i++) {
  const r = rows.find(x => x.idx === i);
  console.log(r ? `  ${String(i).padStart(2)}  ${r.sat}   ${r.blockHeight}  ${String(r.hashTail).padStart(3)}  ${r.date}`
                : `  ${String(i).padStart(2)}  — not inscribed —`);
}

const body = Array.from({ length: N }, (_, i) => {
  const r = rows.find(x => x.idx === i);
  const d = ds[i]?.date ?? '?';
  return r
    ? `  { inscriptionId: "${r.inscriptionId}", hashTail: ${r.hashTail}, inscriptionUnix: ${r.inscriptionUnix}, blockHeight: ${r.blockHeight}, sat: ${r.sat} }, // piece ${String(i).padStart(2,'0')} — ${d}`
    : `  null, // piece ${String(i).padStart(2, '0')} — ${d} — not yet inscribed`;
}).join('\n');

const out = `// inscriptions.ts — GENERATED by cessation/sync-tracker.mjs. Do not edit by hand.
//
// Regenerate with:  cd ../cessation && node sync-tracker.mjs --write
//
// Every value here was read from the chain: children from the engine's /r/children,
// hashTail and inscriptionUnix from each piece's own CBOR metadata decoded with the
// ENGINE's decoder, blockHeight from ord. Nothing is transcribed by hand, because
// hand-maintained copies of on-chain data are how this project's notes went stale.
//
// Generated ${new Date().toISOString()} — ${rows.length} of ${N} pieces inscribed.

export interface PieceInscription {
  inscriptionId: string;
  hashTail: number;        // 0–99
  inscriptionUnix: number; // Unix seconds
  blockHeight: number;     // block the reveal confirmed in
  sat: number;             // the rare sat this piece lives on
}

// Index matches piece index. null = not yet inscribed.
export const PIECE_INSCRIPTIONS: (PieceInscription | null)[] = [
${body}
];

export const ENGINE_INSCRIPTION_ID: string | null = ${rows.length ? `"${ENGINE}"` : 'null'};
`;

const SHARED = [
  ['data/health_data_sets.js', 'src/data/health_data_sets.js'],
  ['data/decay_logic.js',      'src/data/decay_logic.js'],
  ['src/shaders/fragment.glsl','src/shaders/fragment.glsl'],
  ['src/shaders/vertex.glsl',  'src/shaders/vertex.glsl'],
];

// The tracker imports these files as ES modules. cessation's copies already carry
// their own `export { ... }` lines, so a plain copy is correct -- but a name the
// tracker imports could disappear in a refactor, and the failure would surface as a
// broken build in the other repo rather than here. So verify before copying.
//
// (An earlier version of this script APPENDED an export line, which produced
// "SyntaxError: Duplicate export". That was my own truncated grep concluding the
// source had no exports. Check the whole file, not the first dozen lines.)
function verifyExports(srcPath, destPath, srcText) {
  if (!/\.js$/.test(srcPath) || !existsSync(destPath)) return;
  const names = (s) => {
    const out = new Set();
    for (const m of s.matchAll(/^export \{([^}]*)\}/gm))
      m[1].split(',').map(x => x.trim().split(/\s+as\s+/).pop()).filter(Boolean).forEach(n => out.add(n));
    for (const m of s.matchAll(/^export\s+(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gm))
      out.add(m[1]);
    return out;
  };
  const had = names(readFileSync(destPath, 'utf8'));
  const has = names(srcText);
  const lost = [...had].filter(n => !has.has(n));
  if (lost.length) {
    console.error(`\n  REFUSING: ${srcPath} no longer exports ${lost.join(', ')},`);
    console.error(`  which ${destPath} currently provides. Syncing would break the tracker build.`);
    process.exit(1);
  }
}

if (!WRITE) {
  console.log(`\n(report only — pass --write to apply)`);
  for (const [a, b] of SHARED) {
    const same = readFileSync(join(ROOT, a)) .equals(readFileSync(join(TRACKER, b)));
    console.log(`  ${same ? 'same    ' : 'WOULD COPY'}  ${a}`);
  }
} else {
  writeFileSync(join(TRACKER, 'src/data/inscriptions.ts'), out);
  console.log(`\nwrote src/data/inscriptions.ts (${rows.length}/${N} inscribed)`);
  for (const [a, b] of SHARED) {
    const dest = join(TRACKER, b);
    verifyExports(a, dest, readFileSync(join(ROOT, a), 'utf8'));
    copyFileSync(join(ROOT, a), dest);
    console.log(`  copied ${a}`);
  }
}
